### ISSUE TITLE
[Suggestion] Show exact user count somewhere in the website (maybe front page)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/website-v2#102]
Chrome Web Store is stuck in multiples of 10,000 but the exact user count is still available as an HTML comment in the normal store page:
![image](https://user-images.githubusercontent.com/17484114/127788989-a49070d2-0c07-475c-9ed4-ec3fc0369e38.png)
And Firefox Add-Ons has visible exact counts in the store page.
We could add these numbers together and show the result somewhere.
And possibly with [odometer](https://github.hubspot.com/odometer/docs/welcome/) :P

**Comment by WorldLanguages** [comment]
https://scratchaddons.com/usercount.json

**Comment by Hans5958** [comment]
Last time I was considering this when creating the whole index page. Maybe do another Cloudflare Workers instance or something.

Or, maybe, let's merge all the API while we're at it. IDK.

**Comment by RedGuy12** [comment]
the exact user count is no longer in a cws comment. that's why https://scratchaddons.com/usercount.json (which is a cf worker), is broken

**Comment by Hans5958** [comment]
By the way, shouldn't this be in a seperate subdomain? That placement is weird.

**Comment by WorldLanguages** [comment]
I didn't want to mess with CORS, lol

**Comment by Hans5958** [comment]
That's a jank
