### ISSUE TITLE
Show min supported version

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/website-v2#11]
Currently we use these features:
- optional chain (es2020; Cr80, FF74)
- globalThis (es2020, Cr71, FF65)
- RelativeTimeFormat (Cr71, FF65)
- DateTimeFormat timeStyle, dateStyle (Cr76, FF79)

we should probably show the min supported version (80)

**Comment by WorldLanguages** [comment]
It would be great to have a page of the website we can open when users try to interact with the extension with an unsupported browser, that tells them to update
