### ISSUE TITLE
`addon-basics` page does not exist.

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/website-v2#125]
The [_Creating an Addon_](https://scratchaddons.com/docs/develop/getting-started/creating-an-addon/) page links to [`https://scratchaddons.com/docs/develop/getting-started/creating-an-addon/addon-basics`](https://scratchaddons.com/docs/develop/getting-started/creating-an-addon/addon-basics), but all that leads to is a 404 error.

**Comment by RedGuy12** [comment]
Feel free to pr

**Comment by Hans5958** [comment]
Seems fixed on #139.
