### ISSUE TITLE
Better navbar layout

### ISSUE THREAD

**Issue by Ascor8522** [ScratchAddons/website-v2#126]
The current navbar layout is weirdly organized, with the most useful links not being palced first.
I'd suggest changing it to a more conventionnal layout.

## Current:
* language selector
* contributors
* feedback
* repo
* install

## Sugested:
* install (first step to do, so must come 1st)
* addons list (important info, so must come 2nd)
* feedback (happens after install, so 3rd)
* docs (for new users to contribute, isn't required imo but nice to have)
* repo (last important link imo)
* language selector (always last, near the corner)

## Examples
See navbar layout on some random tech websites

<details>
  <summary>Nodejs</summary>

  * home
  * dowloads
  * docs (feature list => same as SA addons list )
  * get involved (to contribute => same as SA  docs)
  * language selector

</details>
<details>
  <summary>SASS</summary>

  * install
  * learn / doc (=> features list => SA addons list)
  * get involved (to contribute => same as SA docs)
</details>
<details>
  <summary>React</summary>

  * docs (=> features list => SA addons list)
  * languages selector
  * repo
</details>
<details>
  <summary>Socket.io</summary>

  * doc / server api / client api (=> features list)
  * comminuty > repo
  * language selector
</details>
<details>
  <summary>RxJS</summary>

  * overview (=> install + features list)
  * reference (=> contribute)
  * repo
</details>
<details>
  <summary>TypeScript</summary>

  * download
  * doc (=> feature list)
  * community > repo
</details>
<details>
  <summary>Jest</summary>

  * docs > install
  * docs > guides (=> features list)
  * language selector
  * repo
</details>

**Comment by WorldLanguages** [comment]
I agree on that the current order is weird

**Comment by Hans5958** [comment]
Last time I implemented this, I have no clue what to put there. It was a combination of the previous website interation, as well as trying to put the links that the website is often used (namely the send feedback, and the credits).

I agree this has to change, while also balance it so it is not too much. I am quite both surprised and unsurprised that this hasn't change for months.

**Comment by RedGuy12** [comment]
> I am quite both surprised and unsurprised that this hasn't change for months.

this repo is quite dead tbh

**Comment by Hans5958** [comment]
I was just fiddling with the navbar, and I came out with this.

**Comment by WorldLanguages** [comment]
@Hans5958 Looks nice, I'm just not that convinced about making the "send feedback" button easier to reach.

**Comment by Hans5958** [comment]
I'm unsure whether it will change the source. Most people got into the page from the extension, but I'm unsure if that's a correct way to intepret the analytics.

**Comment by Hans5958** [comment]
I was also thinking about doing the theme toggle to the top, just like what we did on the extension.
