### ISSUE TITLE
Error 404: Page does not exist

### ISSUE THREAD

**Issue by TomatoNotFound** [ScratchAddons/website-v2#133]
When I click to Scratch Extensions. It leads me to the error 404 page

**Comment by WorldLanguages** [comment]
What's the URL?

**Comment by TheColaber** [comment]
Seems to be this link on scratchaddons.com:
![image](https://user-images.githubusercontent.com/72760579/142081366-3b0369a8-0dff-410c-827c-d7be21072f1c.png)
