### ISSUE TITLE
Do not encourage users to send feedback

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/website-v2#142]
Feedback from the feedback form:
* can't be reviewed by others.
* can't be given feedback.
* can't have a PR automatically able to close it.
* is harder to track.

**Comment by WorldLanguages** [comment]
Sure, how it currently works is not ideal. But what's the alternative? The current way reduces friction since users don't need to create a GitHub account.
I think it makes more sense to have a system where feedback ends up in a repo after an org member can review each message.

**Comment by CST1229** [comment]
>- can't be given feedback.

Do you mean a response? It can be, if some form of contact is entered.

**Comment by Secret-chest** [comment]
> Sure, how it currently works is not ideal. But what's the alternative? The current way reduces friction since users don't need to create a GitHub account. I think it makes more sense to have a system where feedback ends up in a repo after an org member can review each message.

Maybe a bot that sends feedback to this repo in new issues?

**Comment by apple502j** [comment]
Some requests contained inappropriate stuff, so automating is not possible.

Feedback via the feedback form is better than not getting a feedback at all. Closing

**Comment by Secret-chest** [comment]
> Some requests contained inappropriate stuff, so automating is not possible.
> 
> Feedback via the feedback form is better than not getting a feedback at all. Closing

But sending it after review?

**Comment by RedGuy12** [comment]
> But sending it after review?

We often do

**Comment by WorldLanguages** [comment]
@Secret-chest The Glitch server is open source, maybe you could contribute a button on the embed that uses [GitHub URL parameters](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query) to make it easier for us to make feedback public after we review it on the Discord server?

**Comment by RedGuy12** [comment]
@WorldLanguages afaik buttons need a bot?

**Comment by WorldLanguages** [comment]
@RedGuy12 I meant a link

**Comment by Secret-chest** [comment]
> The Glitch server is open source

Link?

**Comment by WorldLanguages** [comment]
https://glitch.com/edit/#!/scratchaddons-feedback

**Comment by RedGuy12** [comment]
isn't it https://github.com/ScratchAddons/feedback-server?

**Comment by WorldLanguages** [comment]
@RedGuy12 Graham made that repo but I didn't keep it up to date.
