### ISSUE TITLE
Outdated code example in userscript documentation

### ISSUE THREAD

**Issue by Norbiros** [ScratchAddons/website-v2#143]
### Description

When you use `addon.auth.username` it will return `undefined`.

### Repoduction steps

1. Fork newest scratch addons
2. Create new addon
3. Add code from https://scratchaddons.com/docs/develop/addon-types/userscripts/ to it.
4. Save, reload, add to browser and open console

### Expected behaviour

It should send name of user.

### Environment

- Browser: Firefox/95.0
- Scratch Addons version: Newest
- Operating system: Unix - Gentoo

**Comment by WorldLanguages** [comment]
Maybe I should take a whole day tomorrow fixing the docs

**Comment by Norbiros** [comment]
Thanks you verry much 😸, but can someone tell me please how to use it next? `.then` things... 
I tried adding it, but i can for example make it to work with `console.log`, but I want to have variable with `user's name`.

**Comment by mxmou** [comment]
> Thanks you verry much 😸, but can someone tell me please how to use it next? `.then` things... I tried adding it, but i can for example make it to work with `console.log`, but I want to have variable with `user's name`.

You can use `await` for that:
```js
const username = await addon.auth.fetchUsername();
```

**Comment by Norbiros** [comment]
Thanks again!
**That's why I like community scratch the most - nice and always helpful! **
