### ISSUE TITLE
Support Edge store

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/website-v2#150]
- [x] Detect Edge user agent for automatic install button on navbar and homepage
- [x] Add Edge button at the bottom of homepage, in the middle between Chrome and Firefox

**Comment by Hans5958** [comment]
Released? Let's go!

**Comment by Hans5958** [comment]
I don't know why we have griffpatch as the name there, and not "Scratch Addons" or "ScratchAddons.com".

Anyways, this should be quick. Expect PR later.

**Comment by RIMOPA** [comment]
> Released? Let's go!
I think not yet! (24/2/2022)
![image](https://user-images.githubusercontent.com/97112832/155653202-e2e35063-191b-4725-aa53-2ab0814e64e0.png)

**Comment by RedGuy12** [comment]
it's currently hidden from search bc wl messed up and said we only support english

**Comment by Hans5958** [comment]
If you aren't on the development server, here's the link (the server is a public space):

https://microsoftedge.microsoft.com/addons/detail/iliepgjnemckemgnledoipfiilhajdjj
