### ISSUE TITLE
More precise the tutorials

### ISSUE THREAD

**Issue by Evrick14** [ScratchAddons/website-v2#164]
The thing is in the tutorials from SA. the tutorials are not really precise when the addon is a bit more complicated to explain/use for an example the debbuger: When i saw this part of the video i didn't understood how to use it. Like in the video Aidan or CoolScratcher(i don't remember who was talking) wasn't explaning in depth. So to conclude, i just want to explain more in depth the addons's subject in video

**Comment by apple502j** [comment]
This is not the correct place to report these - use the general feedback form or go to the Discord server. https://scratchaddons.com/feedback/
