### ISSUE TITLE
Website suggested features

### ISSUE THREAD

**Issue by Wjplatformer** [ScratchAddons/website-v2#169]
# Suggested features for website:
![image](https://user-images.githubusercontent.com/82447031/157236918-f6b62051-d60d-4c43-8a8c-d99c9050c29d.png)
- sticky navbar, for good accessibility to the repo and other pages
- in this part of the homepage, make some of the titles on under the `features` part (home page) links if unable for sticky navbar to be made as it is a bit troublesome to scroll up especially when the website expands. If not, we can direct it to the top of the  page
- any more suggestions?

**Comment by Hans5958** [comment]
I really dislike the idea of sticky navbar. There is even [an adblock filter](https://github.com/yourduskquibbles/webannoyances) to remove these sticky elements. So, I won't do it, but I did sticky elements when the space is not used effectively, such as docs TOC and pages.

I kinda don't get it on the second one.

I will open this for a few days and then closing, in case anyone want to give opinion.

**Comment by mxmou** [comment]
> I really dislike the idea of sticky navbar.

It's useful because you don't have to scroll up to access another page. Scratch has it too, so users will probably expect it.

**Comment by Hans5958** [comment]
It is true if the items of the navbar is frequently used. Otherwise it is enough to count is as a hindrance.

**Comment by Secret-chest** [comment]
I have a sticky navbar on my site, but it's very small, only 48px.

**Comment by Wjplatformer** [comment]
> I really dislike the idea of sticky navbar. There is even [an adblock filter](https://github.com/yourduskquibbles/webannoyances) to remove these sticky elements. So, I won't do it, but I did sticky elements when the space is not used effectively, such as docs TOC and pages.
> 
> I kinda don't get it on the second one.
> 
> I will open this for a few days and then closing, in case anyone want to give opinion.

I get it. The style of the website is what it is. I now feel that the navbar is kinda ok I guess, it seems more minimalist than a big one.
<br>
For the second one, like the `open source` title in the part of the home page (in picture) can be a link to the `Credits` page.
<br>
Also, another improvement is to move the `Language Preference` dropdown in the navbar after the `Send Feedback` (link or button?). This places importance on the other pages rather than the language and seems a bit of a hindrance and annoyance to see the language preference right at the front (not saying we should disrespect other languages). The scratch website's language preference is all the way down. So I feel this is a little better for visitors on the website.

**Comment by Hans5958** [comment]
> For the second one, like the "open source" title in the part of the home page (in picture) can be a link to the "Credits" page.

I see. I wouldn't do it on the title as it is not consistent with the other consistent. If I do I would link it on the repository (that's the source (code) of open source), not the credits. But, I'll see what people think about it.

> Also, another improvement is to move the Language Preference dropdown in the navbar...

That discussion is on #126. A friendly rule is to have one issue for one problem, not compile it into one issue.

**Comment by Wjplatformer** [comment]
okay thanks. Take note of the rule :)
