### ISSUE TITLE
Allow switching to any language on any page

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/website-v2#170]
Going to a page that isn't translated changes the navigation bar to English, which is confusing. It also makes all links lead to English pages, so the user needs to select the correct language again after clicking a link on an untranslated page. The website would be easier to use if it was possible to select a different language even if the content of the current page isn't translated.

**Comment by Hans5958** [comment]
I think it is a continuation of your issue of having all languages pages to be shown, even it is not translated, full-stop. So, I think this should continue on #92.

**Comment by mxmou** [comment]
> I think it is a continuation of your issue of having all languages pages to be shown, even it is not translated, full-stop. So, I think this should continue on #92.

#92 can be fixed without doing this by simply adding links to the English pages.

**Comment by Hans5958** [comment]
Not that simple in terms of Hugo.

**Comment by WorldLanguages** [comment]
> Not that simple in terms of Hugo. Only option is to generate all untranslated pages by copying the English pages.

Could you list the reasons why this shouldn't be done?

**Comment by Hans5958** [comment]
Are you talking about how Hugo works or why I don't just copy all the English pages? 

Hugo works as a static site generator. All the pages, including the language selector, is generated beforehand. It's not dynamic like Vue, so you can't just have a single page to appear "English" and "Deutsch" in the same time, that's not how it works. (You can do JS, but that's the point of "it is not that simple"). The easier way is to just copy **ALL** English pages to those who haven't been translated.

About I don't just copy all the English pages, it has been explained on #92, but the pretense is "it is weird to have untranslated pages to be seen by everyone."
