### ISSUE TITLE
Languages on the website are *still* not working

### ISSUE THREAD

**Issue by Wjplatformer** [ScratchAddons/website-v2#210]
### Hey ScratchAddons team,
Most of the languages on the scratchaddons website don't change the content text to that language. And some languages like chinese do not even have the navbar text changed<br>
![language issue on SA website v2](https://user-images.githubusercontent.com/82447031/173178270-68fd1418-5dbb-4624-bd94-ca50e374bcbf.png)

I can contribute if this is meant to be done manually, but if not, something is wrong. I found issue #99 which is about the website, but there are still languages that can be translated<br>
![image](https://user-images.githubusercontent.com/82447031/173178449-0ee25bc4-2799-4407-8450-56b8b52c515f.png)
![image](https://user-images.githubusercontent.com/82447031/173178553-65437fc5-6d8a-4173-9ed7-41c5ebffaf6d.png)
##### *from W3Schools
We can translate the whole page now using google translate but it doesn't seem to work on the content in the website :/

**Comment by Norbiros** [comment]
We are translating strings using Transifex.
It isn't translated because no one translated this string to specific language.
If you want to help us translating Scratch Addons, and Scratch Addons Website: https://www.transifex.com/scratch-addons/scratch

**Comment by Wjplatformer** [comment]
Welp, alright then :)

**Comment by Wjplatformer** [comment]
> We are translating strings using Transifex, so people translate all strings manually. This message isn't translated, because no one translated this to specific language. If you want to help us translating Scratch Addons, and Scratch Addons Website: https://www.transifex.com/scratch-addons/scratch

I don't mean to say this message because why would I want a translated version of this message

**Comment by Wjplatformer** [comment]
I deleted some messages because I found out that I needed to have a transifex account so sorry

**Comment by Wjplatformer** [comment]
@Norbiros, I have sent a request to be in the Scratchaddons Transifex team so I was wondering if anyone would accept (or deny) this request :)

**Comment by Norbiros** [comment]
You can go on our Dev discord server. Or just DM WL or apple

**Comment by Wjplatformer** [comment]
Thanks!
