### ISSUE TITLE
Improve addon highlights

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/website-v2#230]
I like the scrolling highlights, but I think it could be improved.

![compressed_sa-highlights](https://user-images.githubusercontent.com/81489795/181052463-d26f2b9d-86f2-4673-af2d-0c6eb508ab95.jpg)

- Make all addons the same height adding blank space to ones with shot descriptions and `...` to long ones.
- Replace any addon that doesn't have an image with one that does
- Pick some addons with really good screenshots, even if they're not the most popular addons

**Comment by Hans5958** [comment]
I'm not sure whether having it hand-picked would be better. I wanted to try to avoid "things that needed to be checked and updated."

I would see what I can do about the same width, and I would rather keep the non-image addons for now.

**Comment by Samq64** [comment]
Aren't they already hand picked?

**Comment by Hans5958** [comment]
The one appeared on the carousel is the ones that have the `recommended` tag in it. In a way of thinking that by doing that, it is hand-picked, because adding it also requires human decision, then yes.

**Comment by WorldLanguages** [comment]
@Hans5958 Thanks! They look better now
