### ISSUE TITLE
Dark mode button's description does not change

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/website-v2#26]
Look.
![ScratchAddonsBug](https://user-images.githubusercontent.com/74276537/118493528-d5c31f80-b6e6-11eb-9597-b10cbfa363aa.png)

**Comment by RedGuy12** [comment]
Toggle means "change the state of". So toggling can mean turning off or on. I agree that a better description might be better, but it's probably not a high priority.
________________________________
From: 22yeetz22 ***@***.***>
Sent: Monday, May 17, 2021 8:07:22 AM
To: ScratchAddons/website-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/website-v2] Dark mode button's description does not change (#26)


Look.
[ScratchAddonsBug]<https://user-images.githubusercontent.com/74276537/118493528-d5c31f80-b6e6-11eb-9597-b10cbfa363aa.png>

**Comment by Hans5958** [comment]
I'm using the word "toggle" so it only uses one single sentence instead of two. If there are two sentences, I need to program to swap the text.
