### ISSUE TITLE
Translating images

### ISSUE THREAD

**Issue by RIMOPA** [ScratchAddons/website-v2#262]
For example, when users go to the docs, they hope to see a full representation of the information they need or the solution to their problem. But when the users see something in another language, especially if they don't understand that language, they feel uncomfortable. Currently, all the users have a 100% of probability of see every image in English, so yes. If we add a system for translating images, we have more probabilities of happy users, positive reviews, etc.

**Comment by penguinmoose** [comment]
Good idea. For the screenshots of or containing Scratch, we can simply change the language of Scratch in the screenshot.

**Comment by WorldLanguages** [comment]
The problem with "translated images" is that ensuring consistency is hard.
