### ISSUE TITLE
Fixed navbar on scroll

### ISSUE THREAD

**Issue by surya-doc** [ScratchAddons/website-v2#263]
The idea is when we'll scroll the website the navbar should stick to the top of the page. If this feels legit can I work on this issue?

**Comment by surya-doc** [comment]
If this feels legit can I work on this issue?

**Comment by WorldLanguages** [comment]
I think it's intentionally not sticky.

**Comment by Hans5958** [comment]
👋 It has been considered that a sticky navbar would be needed for the current use case. Thanks for the opinion, still.
