### ISSUE TITLE
Docs: change color pallete used for code blocks

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/website-v2#278]
The current colors are not very appealing to the eye:
![image](https://user-images.githubusercontent.com/17484114/205160487-ae1db18b-73d1-4678-aa1e-567f134ef8ff.png)

Personally, I would change the codeblock style to [one-dark](https://pygments.org/styles/#one-dark), which looks similar to VS code default colors:
![image](https://user-images.githubusercontent.com/17484114/205160588-20e3feda-4be6-4985-baa2-f579dd9a50a8.png)

**Comment by RedGuy12** [comment]
I like one dark too, but um...that's nothing like VS Code Dark, that's based on Atom One Dark


________________________________
From: World_Languages ***@***.***>
Sent: Thursday, December 1, 2022 3:15:51 PM
To: ScratchAddons/website-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/website-v2] Docs: change color pallete used for code blocks (Issue #278)


The current colors are not very appealing to the eye:
[image]<https://user-images.githubusercontent.com/17484114/205160487-ae1db18b-73d1-4678-aa1e-567f134ef8ff.png>

Personally, I would change the codeblock style to one-dark<https://pygments.org/styles/#one-dark>, which looks similar to VS code default colors:
[image]<https://user-images.githubusercontent.com/17484114/205160588-20e3feda-4be6-4985-baa2-f579dd9a50a8.png>

**Comment by WorldLanguages** [comment]
Related recent PR: #277
