### ISSUE TITLE
Create a new blog page on the v1.30 update

### ISSUE THREAD

**Issue by BroJac5246** [ScratchAddons/website-v2#286]
So far there's only one post on the [blog](https://scratchaddons.com/blog/). We should probably use it! v1.30 is about to release, so this would be a good opportunity to add one.

Also, is there any documentation on adding a new blog post?

**Comment by WorldLanguages** [comment]
> Also, is there any documentation on adding a new blog post?

I'm not sure.

**Comment by BroJac5246** [comment]
> > Also, is there any documentation on adding a new blog post?
> 
> I'm not sure.

That would also be useful.

**Comment by Hans5958** [comment]
Anyone is welcome to write on the blog.

It is on https://github.com/ScratchAddons/website-v2/wiki/Creating-a-blog-post.

**Comment by tonyzhigit** [comment]
> It is on https://github.com/ScratchAddons/website-v2/wiki/Creating-a-blog-post.
That should be on the [blog post](https://scratchaddons.com/blog/) or the [SA documentation](https://scratchaddons.com/docs/)

**Comment by BroJac5246** [comment]
> > It is on https://github.com/ScratchAddons/website-v2/wiki/Creating-a-blog-post.
> 
> That should be on the [blog post](https://scratchaddons.com/blog/) or the [SA documentation](https://scratchaddons.com/docs/).
> 

The Scratch Addons docs are for _addon_ development, and the blog is meant to be public-facing.

I would appreciate if it were more prominent, but don't know how that would work.
