### ISSUE TITLE
Absolute paths links to English docs on non-English docs

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/website-v2#296]
### Description

In the website, some links to the documentation bring the reader to English language pages, even if they are reading the documentation in a different language.

### Steps to reproduce

1. go to https://scratchaddons.com/it/docs/develop/getting-started/creating-an-addon/
2. click the linked words "informazioni di base sugli addon"
3. the user is brought to https://scratchaddons.com/docs/develop/getting-started/addon-basics/ instead of https://scratchaddons.com/it/docs/develop/getting-started/addon-basics/

### Environment

Browser: Firefox 109
Scratch Addons version: 1.30.1
Operating system: macOS Big Sur

**Comment by WorldLanguages** [comment]
@Hans5958 How is this supposed to work?

**Comment by Hans5958** [comment]
Ah, I forgot to make that work. Bear with me while I try to make the script so it links to the proper translated page.

> How is this supposed to work?

I assume to just convert the links of absolute paths to the translated parts, except those that aren't being translated.

**Comment by Hans5958** [comment]
The patch has been implemented and it seems that it works as expected. You may test again if you want.

**Comment by sfederici** [comment]
The link I indicated in the example now works. There are other links that instead still do not work as expected, e.g. the link "queste istruzioni" ("these instructions") at page https://scratchaddons.com/it/docs/develop/getting-started/creating-an-addon/ that links to https://scratchaddons.com/docs/getting-started/installing/#from-source.

**Comment by Hans5958** [comment]
This also has been fixed on d510f0d86c44df5ec2642f047d7df9f0b8005712. You have to wait for the next sync, then you have to retranslate that.
