### ISSUE TITLE
Multiple grammar errors in README

### ISSUE THREAD

**Issue by fractioneater** [ScratchAddons/website-v2#298]
I'm too lazy to create a PR, so I'll just put this in an issue:

### Current Version
These are the files behind the Scratch Addons website. It is build with Hugo as the static site generator, Bootstrap 4 as the CSS framework, and GitHub Pages as the hosting provider. The website is built simple with accessibility and readability in mind, and is mobile-compatible.

### Suggested Changes
- Replace the first "build" with "built"
- Replace "built simple" with "built to be simple"

Also, I feel like the entire thing could be reworded to sound better.

**Comment by DNin01** [comment]
"Simple" might be intentional. It sounds to me like "built to be simple". "Built simple".

**Comment by BroJac5246** [comment]
> "Simple" might be intentional. It sounds to me like "built to be simple". "Built simple".

That's probably the case, although it's not very clear that way.

**Comment by DNin01** [comment]
> > "Simple" might be intentional. It sounds to me like "built to be simple". "Built simple".
> 
> That's probably the case, although it's not very clear that way.

Yeah, there's still room for improvement.

**Comment by fractioneater** [comment]
> "Simple" might be intentional. It sounds to me like "built to be simple". "Built simple".

This makes sense. I've updated the original comment.
