### ISSUE TITLE
data category tweaks not working. zero effect. 

### ISSUE THREAD

**Issue by ksdavidc** [ScratchAddons/website-v2#316]
only addon active. NADA

tried signed in signed out different accounts...not sure where to go from here.

<img width="1537" alt="Screen Shot 2023-04-01 at 1 06 51 PM" src="https://user-images.githubusercontent.com/62230004/229264863-1f4c5030-f8c8-4bc2-88e9-fc51df9cd87f.png">

[scratch.mit.edu-1680322410143.log](https://github.com/ScratchAddons/website-v2/files/11128422/scratch.mit.edu-1680322410143.log)

got a ton of errors in the console, attached

**Comment by ksdavidc** [comment]
I just realized this is the wrong repository. Not sure how I ended up here. Apologies, please ignore

**Comment by Samq64** [comment]
This is a know issue. See https://github.com/ScratchAddons/ScratchAddons/discussions/5860.

**Comment by ksdavidc** [comment]
Holy Happy Obfuscations Batman, that would have been hard to find! Thanks!
