### ISSUE TITLE
SEO / crawling problem

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/website-v2#34]
![image](https://user-images.githubusercontent.com/64214252/119367091-9b75f700-bc7f-11eb-8bfd-a167a0dff0f8.png)
The real problem is that English links to `/ar`. 🤦

**Comment by Hans5958** [comment]
Pretty weird that Google indexes the language dropdown. I can't see it from here when searching Googe, but I have made commit cf746680. I can't confirm if solves the problem, so I'm keeping this open.

**Comment by Hans5958** [comment]
@GrahamSH-LLK, any updates?

**Comment by GrahamSH-LLK** [comment]
Nope, still there. @WorldLanguages Can you recrawl /?

**Comment by WorldLanguages** [comment]
> Nope, still there. @WorldLanguages Can you recrawl /?

Apparently I asked Google to recrawl

**Comment by Hans5958** [comment]
Updates?

**Comment by GrahamSH-LLK** [comment]
Nope. STILL there

**Comment by Ascor8522** [comment]
Looks like that problem got solved / is no longer relevant.

![image](https://user-images.githubusercontent.com/17651422/155531999-b52d5369-1009-4082-b3cf-6c9fea04f454.png)
![image](https://user-images.githubusercontent.com/17651422/155532028-cf7e6fd2-d1bf-43b2-b986-cea85c89ab93.png)
