### ISSUE TITLE
Create blog post for v1.33.0

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/website-v2#340]
I would be interested in writing the next blog post. Let me know if you have any comments or ideas.

**Comment by DNin01** [comment]
> There should probably be a list of known issues and then let users know they will be fixed in 1.33.1.

What kinds of known issues?

**Comment by Samq64** [comment]
There's https://github.com/ScratchAddons/ScratchAddons/issues/6103 and a couple website addons that don't use the purple yet.

**Comment by DNin01** [comment]
> There's https://github.com/ScratchAddons/ScratchAddons/issues/6103 and a few website addons that don't use the purple yet.

I would hope v1.33.1 comes out before or right after the Scratch update so these issues aren't observed.

**Comment by Hans5958** [comment]
How's the blog post?

**Comment by Secret-chest** [comment]
I'm also interested. I can write it _today_.
