### ISSUE TITLE
`/addons` has really bad loading

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/website-v2#35]
When you load `/addons` for the first time, (repro by clearing cache), it looks like the page is having a seizure.
This is caused by the images loading slowly, afaik

**Comment by Hans5958** [comment]
I think I have ever mentioned it somewhere about this, but here it goes again.

I actually thought about this when designing the addons page, I have two options.

- To hide all the addons until everything is loaded. This only result a single content shift, but will need the user wait without any clear indication
- To show all the addons and let the images loaded. This results a heck ton of content shift, but let's the user know that something is loading.

I chose the later at the time, and here we are. LMK what you think about it.

**Comment by Ascor8522** [comment]
> * To show all the addons and let the images loaded. This results a heck ton of content shift, but let's the user know that something is loading.

One solution would be to include the expected size of every image, so that every container in the page already has the right size and images won't cause a content shift once loaded.

A placeholder could be displayed while the images are loading.

This is a quite common solution for webpages with a lot of content, especially images.

**Comment by Hans5958** [comment]
That might be a good idea. The problem is that they could appear in various size, but I presume I could do something with the aspect ratio, which I overlooked. I'll see what I can do.

**Comment by Hans5958** [comment]
Alright. Got the solution. This will be closed on the commit after this reply.
