### ISSUE TITLE
The header doesn't word wrap if words get too long

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/website-v2#364]
The Scratch Addons header in German has the word "Browsererweiterung" cut off on mobile.

![The header with the word "Browsererweiterung" cut off.](https://github.com/ScratchAddons/website-v2/assets/130385691/5e34e947-9d1a-48d9-a4b6-59c0229df16b)

**Comment by WorldLanguages** [comment]
Which header are we talking about?

**Comment by mybearworld** [comment]
I'll add in the picture...

**Comment by WorldLanguages** [comment]
Looks like the h1 in the front page needs `word-wrap: break-word;`

**Comment by mybearworld** [comment]
Probably also `hyphens: auto`

**Comment by Hans5958** [comment]
#327 revamps the page significantly, so hopefully this is done.
