### ISSUE TITLE
Toc shouldn't show when there is no Toc

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/website-v2#38]
To repro, go to https://scratchaddons.com/docs/ and adjust your screen size so you see this button: 
![image](https://user-images.githubusercontent.com/72760579/119493143-e3ebee00-bd2d-11eb-926e-d6aa470eb233.png)
Now try clicking it. Notice that nothing happens

**Comment by GrahamSH-LLK** [comment]
👍

**Comment by Hans5958** [comment]
> I think the TOC should be on the left and the sidebar should stay visible at the top.

I think it is rare to have the pages always appear, probably because they are counter-productive, and most times aren't needed when reading. I'm up for having the TOC always on top (maybe when I learned grids), but not the pages.
