### ISSUE TITLE
Change the copy link icon on docs

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/website-v2#39]
![image](https://user-images.githubusercontent.com/72760579/119493377-21507b80-bd2e-11eb-9aa4-066101abc2e1.png)
weird... i was expecting a link button like when you do a header in github

**Comment by mxmou** [comment]
The ¶ icon is also commonly used for this purpose.

**Comment by TheColaber** [comment]
so is 
![image](https://user-images.githubusercontent.com/72760579/119545733-22e76700-bd61-11eb-9fb6-e9ec7ff45440.png)

**Comment by mxmou** [comment]
But if both are commonly used, is changing it really needed?

**Comment by TheColaber** [comment]
i've honestly never seen ¶ in my life

**Comment by TheColaber** [comment]
it's not universal, or obvious... a link icon is

**Comment by mxmou** [comment]
@TheColaber It's used by the Python documentation (for example https://docs.python.org/3/library/stdtypes.html) and many other projects that use Sphinx for documentation, such as [Requests](https://docs.python-requests.org/en/master/). The most popular Sphinx theme (Read the Docs) uses a link icon though.

**Comment by Hans5958** [comment]
Seems it's a stale one. I'll close it.
