### ISSUE TITLE
Always mention we're not the Scratch Team

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/website-v2#439]
The feedback page has a warning that can trigger telling users we're not the Scratch Team and links to their contact page but it's not completely effective. Why not just always mention it somewhere on the page?

**Comment by BwnnyRxbbit** [comment]
What if I add it straight to the homepage?

**Comment by CST1229** [comment]
> What if we add it straight to the homepage or to the welcome.html page?

Most people sending these kinds of messages through feedback probably got there through Google directly.

**Comment by WorldLanguages** [comment]
> What if we add it straight to the homepage or to the welcome.html page?

Let's not forget that all pages in the footer say: `Scratch Addons is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.` that includes the homepage and welcome pages.

It is also true that we rank relatively high for some Scratch searches like CST said.

**Comment by BwnnyRxbbit** [comment]
> > What if we add it straight to the homepage or to the welcome.html page?
> 
> Let's not forget that all pages in the footer say: `Scratch Addons is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.` that includes the homepage and welcome pages.
> 
> It is also true that we rank relatively high for some Scratch searches like CST said.

Earlier, I took a good look at the homepage and I couldn't find that message. And that text is too tiny and hidden if you want people to see it.

**Comment by Hans5958** [comment]
Two reasons.

1. I believe people would more likely to gloss over a static message (ie. a message that's always shown) than a message that's appear after the action of the user.
2. I'm not sure how you define it being as "not completely ineffective." I saw there's barely any mention of the Scratch Team these days. It's also pretty hard to compare the effectiveness post-PSW and pre-PSW, so I digress.
3. There is a disclaimer on the bottom, as mentioned before by the others, but this would also more likely to be glossed, so I also digress.
