### ISSUE TITLE
Discord link in footer is invalid

### ISSUE THREAD

**Issue by BwnnyRxbbit** [ScratchAddons/website-v2#441]
https://discord.com/invite/R5NBqwMjNc and https://discord.com/invite/Ak8sCDQ 

When I go to either of those links I get a popup saying this: "Safari cannot open the page because the address is invalid."

**Comment by BroJac5246** [comment]
They both work for me in Chrome. We don't support Safari so I'd recommend using a Chromium-based browser or Firefox.

Are you sure Safari is opening the right URL? The error would suggest it isn't.

**Comment by BwnnyRxbbit** [comment]
> They both work for me in Chrome. We don't support Safari so I'd recommend using a Chromium-based browser or Firefox.
> 
> Are you sure Safari is opening the right URL? The error would suggest it isn't.

Ah you're right. I'll close this issue.

**Comment by RedGuy13** [comment]
> We don't support Safari so I'd recommend using a Chromium-based browser or Firefox.

It's just a browser, not sure why it wouldn't work 🤔 
Very odd

**Comment by BwnnyRxbbit** [comment]
> > We don't support Safari so I'd recommend using a Chromium-based browser or Firefox.
> 
> It's just a browser, not sure why it wouldn't work 🤔 Very odd

I'm still able to access the server though. After that alert appears there is a button which redirects me to disc and the server is added to my profile.

I saw another website and the same thing happened so I guess this might be normal. So I closed this issue as not planned.
