### ISSUE TITLE
Addons page redesign

### ISSUE THREAD

**Issue by Bashamega** [ScratchAddons/website-v2#444]
Hello:)
My idea is to add make the box linked to the GitHub repo, or to have a cool hover effect for it.
I would like to work on it.
I already have experience the Hugo so the process will be pretty strait forward for me.

**Comment by Hans5958** [comment]
Duplicate of #271. While I welcome updates, some things have been considered there, so take your time yo read it.

PS. I don't think we necessarily need "cool hover effect" this time.
