### ISSUE TITLE
Revamp contributors/credits page

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website-v2#48]
Some of the ideas are...

- Renaming `contributors.html` to `credits.html`
- Add other kinds of credits such as used libraries, special thanks, etc.
- Do local-based contributor showcase generation process (contributor elements generated on deployment with Hugo instead of client-side JS) (also with commit counts if possible/maybe?)
- Make it translatable (duh)

Some of this are already done on the [`credits-page`](https://github.com/ScratchAddons/website-v2/tree/credits-page) branch. To whom it may concern, please avoid creating a PR of it in the meantime.

**Comment by Hans5958** [comment]
cc @WorldLanguages since you really wanted it

By the way, I just realised that there are two different request. One is to the Cloudflare Workers instance, and another to the contributors repo. Just so you know.

**Comment by Hans5958** [comment]
# Current state (subject to change)

![image](https://user-images.githubusercontent.com/11584103/121379752-89c66c00-c96e-11eb-815e-6e4c711dc323.png)

**Comment by WorldLanguages** [comment]
"share" after "(emoji key)" ??

**Comment by Hans5958** [comment]
> 
> 
> "share" after "(emoji key)" ??

What?

**Comment by WorldLanguages** [comment]
![image](https://user-images.githubusercontent.com/17484114/121381551-3297ab80-c91c-11eb-87cd-600c9bef8084.png)

**Comment by Hans5958** [comment]
Oh lol. I have noticed it but always forgot to do it. Now it has been removed.

**Comment by Hans5958** [comment]
> Here are lists of dependencies Scratch Addons uses to make all of this possible.

I am going to rethink about this wording.

> (xxx License)

I want to avoid users needed to translate all the license names, so I only put the ID.

> its website, and etcetera.

"et cetera" already includes and.

> You, for using Scratch Addons!

I wanted to put it, so it also thanks everyone who only reads it. Dunno.

**Comment by Hans5958** [comment]
I decided to resume development on this one. I finally added commit count and we could deprecate the Workers instance. Twemoji is also implemented, subjectively better.

WL said that he wanted to add a more humble thank you to Griffpatch, so I need to wait him before I can merge.

![Screenshot 2022-02-21 at 14-20-43 Credits](https://user-images.githubusercontent.com/11584103/154907497-03e6a2f4-49da-4512-8c92-c37df4ff73a2.png)

**Comment by Hans5958** [comment]
@WorldLanguages

**Comment by Secret-chest** [comment]
> Twemoji is also implemented, subjectively better

Blobmoji?

**Comment by Hans5958** [comment]
No, I mean the implementation, not what emojis to use.

**Comment by WorldLanguages** [comment]
@Hans5958 There's a gramatical mistake
"but haven't been listed" should be "but hasn't been listed"
I'm not 100% sure but it makes more sense and sounds better

Thanks for the work hans, rest is okay

**Comment by Hans5958** [comment]
I searched Google and it seems you're right. https://linguaholic.com/linguablog/everyone-has-vs-everyone-have/

Anytime. Don't forget for the Griffpatch one that you told me.

PS. Should I add Scratch on the special thanks?

**Comment by WorldLanguages** [comment]
> PS. Should I add Scratch on the special thanks?

Sure

> Anytime. Don't forget for the Griffpatch one that you told me.

I'm not sure how to phrase it either.
Maybe `Griffpatch for making Scratch Addons possible` under "special thanks"?

**Comment by Hans5958** [comment]
I was searching for the word, and I think "jumpstart" is a best word.

Like "Griffpatch for jumpstarting Scratch Addons" or "Griffpatch for jumpstarting Scratch Addons by his Developer Tools extension"

**Comment by CST1229** [comment]
> I was searching for the word, and I think "jumpstart" is a best word.
> 
> Like "Griffpatch for jumpstarting Scratch Addons" or "Griffpatch for jumpstarting Scratch Addons by his Developer Tools extension"

"Griffpatch for jumpstarting Scratch Addons with his Scratch Messaging Extension and Developer Tools extension"

**Comment by Hans5958** [comment]
Oof, sorry, I mean the SME. Scratch Addons is built on top of SME.

**Comment by WorldLanguages** [comment]
I like `Griffpatch for jumpstarting Scratch Addons with his Scratch Messaging Extension` (if that makes sense, I'm not sure if "with" is the right word, we'd need to ask a native speaker)

**Comment by RedGuy12** [comment]
> I'm not sure if "with" is the right word, we'd need to ask a native speaker

that's fine

**Comment by Hans5958** [comment]
Current wording is "Griffpatch for jumpstarting Scratch Addons with his extensions." Should I change it to SME?

**Comment by WorldLanguages** [comment]
@Hans5958 No, it's fine

**Comment by Secret-chest** [comment]
What about WL with Scratch Notifier?

**Comment by Secret-chest** [comment]
Could you change "You!" to "You, for using the extension!"

**Comment by Hans5958** [comment]
> Could you change "You!" to "You, for using the extension!"?

Take your time to read the previous comments.

In any ways, here what I answered last time, and still for today.

> I wanted to put it, so it also thanks everyone who only reads it. Dunno.

**Comment by Secret-chest** [comment]
> > Could you change "You!" to "You, for using the extension!"?
> 
> Take your time to read the previous comments.
> 
> In any ways, here what I answered last time, and still for today.
> 
> > I wanted to put it, so it also thanks everyone who only reads it. Dunno.

But it only says "You!". It's weird.

**Comment by Hans5958** [comment]
No, it's generalized.
