### ISSUE TITLE
Complete localization mechanism

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website-v2#5]
## Checklist

Here's a rough list of things to done now.

- [x] Do hugo-i18n strings on parts of website
- [x] Add language dropdown
- [x] Do script
	- [x] Hugo to i18n (en only)
	- [x] i18n to Transifex (en only)
	- [x] Transifex to i18n (others)
	- [x] i18n to Hugo (others)
	- [ ] i18n to Transifex (others) (?)
- [x] Do integration (with testing)
	- [x] Hugo to i18n (en only)
	- [x] i18n to Transifex (en only)
	- [x] Transifex to i18n (others)
	- [x] i18n to Hugo (others)
	- [ ] i18n to Transifex (others) (?)

## Phases

- [x] Phase 1
	This phase consist of `language.json` and `hugo-i18n.yml`. This will be used for testing and development.
- [x] Phase 2
	This phase consist of the content files (`html-content`, `html-front`, `markdown`). This will be translatable when all the development is done.

**Comment by Hans5958** [comment]
Update: Everything essential should have been working as intended for now. The only issue that I'm facing currently is the fact that Markdown translation aren't downloaded by the Transifex Client. The repository is quite inactive (https://github.com/transifex/transifex-client), so we can't just wait from Transifex to fix it.

**Comment by Hans5958** [comment]
Update that's long due: I have written my own API 3.0 implementation, so now Markdown works. Translation have been expanded to most but not all parts of docs. Closing this for now as it is adequate for now.

**Comment by RedGuy12** [comment]
@Hans5958 how is it used? I need to upload MD files to TX in my own project
________________________________

**Comment by Hans5958** [comment]
It's a little complex, but the way it works here is described here.

Pushing/Uploading:
1. You create the files in this repository.
2. You trigger the script to update the localization files in the i18n repository. (this is done automatically, once a day)
3. You trigger the script to upload the localization files to Transifex (this is done automatically after the previous step)

Pulling/Downloading:
1. You trigger the script to download the localization files from Transifex to the i18n repository (this is done automatically, once a day)
2. You trigger the build script that incorporate the files from the i18n repository. (this is done automatically after the previous step)

I will link the workflows associated with these steps on my laptop later. These workflows have the associated scripts on the script repository. These will run the Bash scripts first, which would include references to the Node.js scripts. I tried my best to make the names descriptive and straightforward, but you should ask me if you are confused in a part of the process.
