### ISSUE TITLE
All l10n on https://scratchaddons.com/pt-br/contributors go to addons

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/website-v2#50]
Go to https://scratchaddons.com/pt-br/contributors, click on the language dropdown, see that all links go to /addons

**Comment by Hans5958** [comment]
Actually, every page were pointing towards /addons on available languages.

Resolved in 37075eb03dc45d6b527af325b4cf66afa732021d

**Comment by RedGuy12** [comment]
Aaa just use ?lang=pt and cookies... that would fix most problems
________________________________
From: GrahamSH ***@***.***>
Sent: Thursday, June 3, 2021 8:53:08 AM
To: ScratchAddons/website-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/website-v2] All l10n on https://scratchaddons.com/pt-br/contributors go to addons (#50)


Go to https://scratchaddons.com/pt-br/contributors, click on the language dropdown, see that all links go to /addons

**Comment by Hans5958** [comment]
> 
> Aaa just use ?lang=pt and cookies... that would fix most problems

Nah, this is a static site, so that does not apply here. The problem is the faulty layout which parts I cached for all pages. The navbar shouldn't be cached because different pages have different translation pages, but I forgot that.

**Comment by WorldLanguages** [comment]
> cookies

no 😡

**Comment by mxmou** [comment]
> > cookies
> 
> no 😡

Currently the user has to choose the language every time they visit the site. I wouldn't call that good user experience.

**Comment by WorldLanguages** [comment]
Local storage works :P

**Comment by TheColaber** [comment]
Why use cookies when lo

**Comment by RedGuy12** [comment]
Or local storage. Same difference
________________________________
