### ISSUE TITLE
Revamp changelog page

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website-v2#53]
I forgot to create this issue on the last batch, so here it is.

- Revamp design of the page
- Add highlights based on the extension
- Make it translatable (partially, not including the entries and highlights)

Some of this are already done on the [`changelog`](https://github.com/ScratchAddons/website-v2/tree/changelog) branch. To whom it may concern, please avoid creating a PR of it in the meantime.

**Comment by Hans5958** [comment]
@WorldLanguages Is it fine for you to add it manually? You need to add the new entries in [data/changelog.yml](https://github.com/ScratchAddons/website-v2/blob/changelog/data/changelog.yml). You can skip the changelog on the main repo if you wish.

**Comment by Hans5958** [comment]
Maybe I could have the highlights translated, but I can't just take what we already have on the main repo, because it is built differently. (The main repo is done in fragments, here is done in a single (Markdown) text. Is it fine for them to translate twice?

**Comment by WorldLanguages** [comment]
Note that I stopped including `Addon development changes:` in the main changelog. Should we go back in time and remove those that are still left from some months ago?

**Comment by Hans5958** [comment]
# Current state (subject to change)

![image](https://user-images.githubusercontent.com/11584103/121379752-89c66c00-c96e-11eb-815e-6e4c711dc323.png)

**Comment by WorldLanguages** [comment]
> Maybe I could have the highlights translated

Define highlights?

**Comment by Hans5958** [comment]
> 
> 
> > Maybe I could have the highlights translated
> 
> Define highlights?

Go check out the current state image

**Comment by WorldLanguages** [comment]
> Is it fine for them to translate twice?

No :P Find a workaround

Also, for v1.16.0 we may make the highlight image link to a YouTube video. So support that if you can (imagine being able to link into a URL)

And honestly, it will be painful for translators to translate the full changelogs. Make sure not to send those for translations before discussing.

**Comment by Hans5958** [comment]
> 
> 
> Note that I stopped including `Addon development changes:` in the main changelog. Should we go back in time and remove those that are still left from some months ago?

It's okay to change history, but it is also okay to keep it. Your call.

**Comment by Hans5958** [comment]
> No :P Find a workaround

No, the problem is that the way it is translated is wayyyyyyyyy different. So much different then I think it is not worth the time to implement it at the moment. (steps include, get all commits, build the different mockup with god knows what way, get the strings, exclude the links, etc, etc, etc)

**Comment by Hans5958** [comment]
> Also, for v1.16.0 we may make the highlight image link to a YouTube video. So support that if you can (image being able to link into a URL)

That's kinda cringe `/s`, but it's possible to have little adjustments. I would like to refer to what is implemented later so I could do the similar layout for it.

**Comment by apple502j** [comment]
Maybe I should provide a JSON API for changelogs. That way we can simplify the process and not have 120 duplicate strings or whatever.

**Comment by Hans5958** [comment]
What's your initial plan with this API?

**Comment by apple502j** [comment]
Just an idea so that you don't have to send raw HTML to Transifex.

**Comment by Hans5958** [comment]
Oh, I thought you are going to build the highlights from the main repo or something like that.

Nah, this part doesn't use HTML. It uses data files, YAML. I may separate the highlights and entry into a single data file, and just upload it into Transifex. These strings would have Markdown.
