### ISSUE TITLE
Broken links on a documentation page

### ISSUE THREAD

**Issue by BarelySmooth** [ScratchAddons/website-v2#54]
**Link to the page:**
[Link](https://github.com/ScratchAddons/website-v2/blob/master/content/docs/develop/getting-started/creating-an-addon.md#step-9-the-fun-part-code) (See step 9, 10, 11)

The links are broken there. Probably a markdown syntax error. It should have been a ```]```, not ```[```

**Comment by Hans5958** [comment]
Kinda duplicate of #51
