### ISSUE TITLE
Add comments for docs (and blog)

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website-v2#57]
I have an idea to add a comment section for the documentation (and the blog in the future).

I have two services in mind to use. Both using GitHub.

- **utterances** (using GitHub Issues, popular, [website](https://utteranc.es), [repository](https://github.com/utterance/utterances), [privacy policy](https://github.com/utterance/utterances/blob/master/PRIVACY-POLICY.md))
- **giscus** (using GitHub Discussions, alternative to utterances, [website](https://giscus.app), [repository](https://github.com/laymonage/giscus), [privacy policy](https://github.com/laymonage/giscus/blob/master/PRIVACY-POLICY.md))

**Comment by GrahamSH-LLK** [comment]
I'm currently using Giscus on my website and it's really nice, but I don't know whether comments go well with docs?

**Comment by Hans5958** [comment]
> I'm currently using Giscus on my website and it's really nice, but I don't know whether comments go well with docs?

Well, I got the idea from Haxe's docs, which I found from utteranc.es. An example is https://haxe.org/manual/introduction-hello-world.html.

**Comment by Hans5958** [comment]
I will continue on this when we got blog merged.

My plan is to use Giscus since I think it is mature enough to be sustainable. (They got sponsor, you know?)

**Comment by Hans5958** [comment]
@WorldLanguages Say that I add giscus to our website, would that need significant changes on the privacy policy? (Just an addition of the list of third-party services is not significant)

**Comment by WorldLanguages** [comment]
@Hans5958 I think it would be fine

**Comment by Hans5958** [comment]
Here are the screenshots until this day. The "code of conduct" link will be linked to the copy on the website. Please tell me whether I need to turn off comments on select pages. If there are no objections then I can start set up Giscus on this repo, some days later.

![image](https://user-images.githubusercontent.com/11584103/157656950-2b8ce1b8-629f-4619-9fe1-87975e6af7de.png)

![image](https://user-images.githubusercontent.com/11584103/157657079-30830e1b-88a4-4386-aa04-bbf8502939d4.png)

**Comment by WorldLanguages** [comment]
@Hans5958 How can we moderate those comments?

**Comment by RIMOPA** [comment]
> @ Hans5958 How can we moderate those comments?
We can use the same thing we use to show Scratch comment warnings

**Comment by Hans5958** [comment]
@WorldLanguages I think it's just like what you do on GitHub Discussions, you can remove messages, lock discussion, etc.

**Comment by WorldLanguages** [comment]
Sounds good enough, since all comments end up on GitHub too
