### ISSUE TITLE
Update addon manifest documentation

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/website-v2#75]
A lot has changed since the last time the addon manifest is updated. There are plenty of things that needs to be updated on the docs.

## 1.10

- [ ] Add `customCssVariables` property with `cssManipulator`
- [ ] Update URL matching based on improvements made
- [x] Add `danger`, `codeEditor`, `costumeEditor`, `projectPlayer`, `editorMenuBar` `projectPage`, `profiles`, `studios`, `comments` options on tags
- [x] Set `community`, `editor`, `popup` tag options to be required as parent categories
- [x] Add `versionAdded` property

## 1.11

- [x] Remove `l10n` property
- [ ] Set `black` and `white` properties on `cssManipulator` to be optional
- [ ] Allow `black` and `white` properties to be `cssManipulator`
- [ ] Allow `cssManipulator` to be a string
- [ ] Add `alphaBend` type on `cssManipulator`
- [x] Add `min` and `max` property on `settings` property with `string` type 
- [ ] Add `recolorFilter` type on `cssManipulator`

## 1.12

- [x] Remove `traps` property
- [x] Add `html` and `script` property on `popup` property

## 1.13

- [ ] Add `alphaBend` type on `cssManipulator`

**Comment by Hans5958** [comment]
Assigned lots of people based on who made the changes on the manifest and the main repo

Related to #74

**Comment by apple502j** [comment]
Ugh, probably means 100+ more to translate? fine, I'll do this.

**Comment by Hans5958** [comment]
It's not a priority, though...

**Comment by Hans5958** [comment]
I also forgot to mention. References are not sent to be translated.

**Comment by RedGuy12** [comment]
Lol why was I assigned I did none of this

Looks like it's mostly cssManipulator which I have no idea how it works lol

**Comment by Hans5958** [comment]
With the advent of March, I will assume that the manifest is up-to-date to the latest manifest. If anyone here thinks it isn't, please reopen it.
