### ISSUE TITLE
Change "forbids advertising browser extensions/userscripts" to "forbids referencing browser extensions/userscripts"

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/website-v2#87]
In the FAQ, specifically https://scratchaddons.com/docs/faq/#can-i-tell-people-about-scratch-addons-on-scratch, it says "there is a policy that forbids advertising browser extensions/userscripts". This should be changed to "there is a policy that forbids referencing browser extensions/userscripts". This is because the Scratch Team doesn't just allow advertising extensions, but also merely referencing them. Reference would also be a much more general term.

**Comment by TheColaber** [comment]
This is quoted from scratch's policy. I don't think we should change it.

**Comment by WorldLanguages** [comment]
Eh, current one is fine, this one would also be fine and more precise, but we're currently quoting Scratch policy soooo...?

**Comment by Hans5958** [comment]
Eh, we're technically not quoting Scratch as the statement is not wrapped in quotation marks, so this may be changed as we please.

**Comment by Hans5958** [comment]
Checking for forgotten resolved issues: The phrase has been changed to "...forbids mentioning...," so this is now resolved. Please reopen if needed.

**Comment by CST1229** [comment]
> Checking for forgotten resolved issues: The phrase has been changed to "...forbids mentioning...," so this is now resolved. Please reopen if needed.

It should be "referencing" - logos are also banned.

**Comment by WorldLanguages** [comment]
@CST1229 I don't think we should consider edge cases like that when choosing the wording.
