### ISSUE TITLE
Docs sidebar only shows translated pages

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/website-v2#92]
Going to https://scratchaddons.com/sl/docs only shows translates pages in the sidebar.

**Comment by Hans5958** [comment]
This is intentional. Really weird to see English pages on other languages.

**Comment by mxmou** [comment]
> This is intentional. Really weird to see English pages on other languages.

It means that people who set the language to Slovenian and click the documentation link can currently only see the page about adding an icon to a setting name in the sidebar. I know what reading partially translated documentation is like, and I don't think it's as weird as this.

**Comment by Hans5958** [comment]
I still stand with my opinion. How I look it is that users mostly prefers the absolute source, the English documentation, instead of using secondary sources. With that I don't think people will get bugged that much.

Still, I think it is easy to implement, so I will try to do it. Obviously there will be some parts that will be excluded like policies. I will fill the languages that at least have something translated on the docs (so no unnecessary long language selector)

**Comment by Hans5958** [comment]
@WorldLanguages Should we do this? Mouse also created #170 for this, so he wants all untranslated pages on the website.

**Comment by Hans5958** [comment]
@apple502j also I don't know

**Comment by WorldLanguages** [comment]
Untranslated strings should be shown in English instead of hiding them

**Comment by Hans5958** [comment]
Yes, that will be the case, but should we show these untranslated page, and all of them?

**Comment by WorldLanguages** [comment]
@Hans5958 I think so

**Comment by Hans5958** [comment]
I have did changes so it will fill untranslated pages with English counterparts. This means that those that are excluded from translation in the first place are not filled. This includes blog and the policies, let me know if this I also need to do this.

**Comment by Hans5958** [comment]
Looking back at it now, it seems that it is more-or-less done. I will close this, but please reopen if you got any more objections or such.

**Comment by WorldLanguages** [comment]
@Hans5958 Is this actually resolved (if not, please reopen this). I remember these messages from the Discord server by ibailba around a year ago.

![image](https://github.com/user-attachments/assets/f9e9e016-4a3a-45b9-965a-429e0360ac96)

**Comment by Hans5958** [comment]
Nope. It sorta continued on #297. What he's talking is basically already discussed on that issue.
